### ISSUE TITLE
A need for Timeline of when what should happen.

### ISSUE THREAD

**Issue by dostiharise** [collabnix/kubezilla#6]
Hey Amazing People of @collabnix and Kubezilla Contributors,

Morning!

Can we have a brief timeline with dates on when I must make myself and my nodes available?

This going to help me plan my time and make my team available for any support activities.

Apologies if you have already shared the details elsewhere, and I couldn't find it. 

Either ways, I think this could be the single source of truth. 

Thanks.

Have a pleasant day!

**Comment by collabnix** [comment]
Hi, we are targeting 27th June starting 2:00 PM till 4:00 PM for Kubezilla.

**Comment by dostiharise** [comment]
Sure. Thanks for the info.
